server:
  port: 8888
spring:
  application:
    name: qs-gateway-demo
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
    nacos:
      server-addr: localhost:8848
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:8888"
            allowedMethods:
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 360000
      routes:
        - id: qs-consumer-demo
          uri: lb://qs-consumer-demo
          predicates:
            - Path=/consumer/**
        - id: qs-user-demo
          uri: lb://qs-user-demo
          predicates:
            - Path=/user/**

