server:
  port: 8082
spring:
  application:
    name: qs-consumer-demo
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
    nacos:
      server-addr: localhost:8848
      logging:
        default:
          config:
            enabled: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qs_comsumer?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: localhost
    port: 6379
    password:
    jedis:
      pool:
        #连接池最大的连接数，若使用负值表示没有限制
        max-active: 8
        #连接池最大阻塞等待时间，若使用负值表示没有限制
        max-wait: -1ms
        #连接池中的最大空闲连接
        max-idle: 8
        #连接池中的最小空闲连接
        min-idle: 0
    #连接超时时间（单位为毫秒）
    timeout: 0
nacos:
  logging:
    default:
      config:
        enabled: false
mybatis:
  mapper-locations: classpath:mapper/*.xml
seata:
  registry:
    type: nacos
    nacos:
      server-addr: localhost:8848
      namespace: ""
      group: DEFAULT_GROUP
      username: nacos
      password: nacos
      application: seata-server
  tx-service-group: seata-demo
  service:
    vgroup-mapping:
      seata-demo: DG
  data-source-proxy-mode: AT
logging:
  level:
    org.springframework.cloud.alibaba.seata.web: debug
    com.ninng: debug
  config: classpath:logback.xml
